name: Terraform PR Validation

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    environment: pre-prod

    defaults:
      run:
        working-directory: env/pre_prod_env

    steps:

      # 1. Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Azure Login using OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Verify Azure authentication
      - name: Verify Azure Login
        run: az account show

      # 4. Secret scanning
      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 6. Terraform formatting
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # 7. TFLint setup
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      # 8. Initialize TFLint
      - name: Initialize TFLint
        run: tflint --init

      # 9. Terraform code quality
      - name: Run TFLint
        run: tflint

      # 10. Terraform security / IaC scan
      - name: Terraform Security Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1



      # 11. Terraform initialization
      - name: Terraform Init
        run: terraform init -backend=false

      # 12. Create Terraform variables file
      - name: Create Terraform variables file
        shell: bash
        env:
          TERRAFORM_TFVARS: ${{ secrets.TERRAFORM_TFVARS }}
        run: |
          printf '%s\n' "$TERRAFORM_TFVARS" > terraform.tfvars

      # 13. Terraform validation
      - name: Terraform Validate
        run: terraform validate

      # 14. Terraform Plan
      - name: Terraform Plan
        run: terraform plan -input=false -no-color
